name: Add Comment to Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate explanation
        id: explanation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Accessing the secret value
        run: |
          python generate_explanation.py "changes"

      - name: Use Explanation in Workflow
        run: |
          echo "Explanation: ${{ steps.explanation.outputs.explanation }}"
          # Use the explanation in subsequent steps of your workflow
          # Example: Add the explanation as a comment to the pull request

      - name: Add Comment to Pull Request
        uses: unsplash/comment-on-pr@master
        with:
          message: ${{ steps.explanation.outputs.explanation }}