name: Add Comment to Pull Request

on:
  pull_request:
  
jobs:
  add_comment:
    runs-on: ubuntu-latest

    outputs:
      explained: ${{ steps.explanation.outputs.explained }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
          pip install PyGithub

      - name: Generate explanation
        id: explanation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Accessing the secret value from github secrets
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
        run: |
          python generate_explanation.py ${{ github.event.pull_request.diff_url }}
          echo "explained=$(python generate_explanation.py ${{ github.event.pull_request.diff_url }} | base64 -w 0 )" >> $GITHUB_OUTPUT

      - name: Use Explanation in Workflow
        run: |
          echo "Explanation: ${{ steps.explanation.outputs.explanation }}"
          # Example: Add the explanation as a comment to the pull request
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Add Comment to Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const comment = `Explanation of Changes:\n\n${{ steps.explanation.outputs.explanation }}`;
      
            async function run() {
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
      
              const newComment = await octokit.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: comment
              });
      
              console.log(`Comment added: ${newComment.data.html_url}`);
            }
      
            run();
