name: Add Comment to Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai
          pip install PyGithub

      - name: Generate explanation
        id: explanation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Accessing the secret value from github secrets
        run: |
          python generate_explanation.py ${{ github.event.pull_request.diff_url }}

      - name: Use Explanation in Workflow
        run: |
          echo "Explanation: ${{ steps.explanation.outputs.explanation }}"
          # Use the explanation in subsequent steps of your workflow
          # Example: Add the explanation as a comment to the pull request

      - name: Add Comment to Pull Request
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github: githubAPI } = require('@actions/github');
          
            const comment = `Explanation of Changes:\n\n${{ steps.explanation.outputs.explanation }}`;
          
            async function run() {
              const newComment = await githubAPI.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: comment
              });
          
              console.log(`Comment added: ${newComment.data.html_url}`);
            }
          
            run();