name: Add Comment to Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate explanation
        run: |
          python generate_explanation.py

      - name: Add Comment to Pull Request
        uses: unsplash/comment-on-pr@master
        with:
          message: ${{ steps.generate_explanation.outputs.explanation }}